//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abastecimiento.WPItemsPedidosConsolidados {
    
    
    public partial class WPItemsPedidosConsolidadosUserControl {
        
        /// <summary>
        /// dtsItemsPedidos control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Microsoft.SharePoint.WebControls.SPDataSource dtsItemsPedidos;
        
        /// <summary>
        /// grvItemsPedidosConsolidados control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Microsoft.SharePoint.WebControls.SPGridView grvItemsPedidosConsolidados;
    }
}
